### ISSUE TITLE
Recommendation Feed

### ISSUE THREAD

**Issue by Mardoqueu** [jlelse/NewsCatchr-OpenSource#16]
How do I add my own Recommendation feed?

**Comment by jlelse** [comment]
What do you mean?

**Comment by Mardoqueu** [comment]
There are a lot of recommendations like: CNN, The New York Times and so on. Where Can I add my won rss link to be in recommendations as well?

**Comment by jlelse** [comment]
You can add your own RSS url by searching for it.

**Comment by Mardoqueu** [comment]
No, I meant straight in the code

**Comment by jlelse** [comment]
Not possible.

**Comment by designthink** [comment]
Then how is the custom recommendation showing up in the play-store version ?
If providing custom feeds are not possible what about custom tags ? For example if i want to make a local language version is it not possible  to provide any customization of recommendation
