### ISSUE TITLE
Can't build project (Unsupported major.minor version 51.0)

### ISSUE THREAD

**Issue by manetivinay** [jlelse/NewsCatchr-OpenSource#9]
Gradle 'NewsCatchr-OpenSource' project refresh failed
Error:Cause: org/gradle/internal/installation/beacon/InstallationBeacon : Unsupported major.minor version 51.0

May be this might be issue with my configuration. I couldn't find out.

**Comment by jlelse** [comment]
@manetivinay I researched a bit and found out, that it might be possible due to an old Java version. What Java version is configured in your IDE and which IDE do you use?

**Comment by manetivinay** [comment]
I'm using Java 8

**Comment by jlelse** [comment]
did you configure Java 8 in the Android Studio settings too?

**Comment by manetivinay** [comment]
Yes
<img width="1280" alt="screen shot 2016-09-10 at 1 40 42 pm" src="https://cloud.githubusercontent.com/assets/7954470/18408519/33fb02ea-775c-11e6-992c-25bde2cfe8a2.png">

**Comment by jlelse** [comment]
@manetivinay I can't really help you. Could you try to find a solution on Google? I'm really sorry.

**Comment by manetivinay** [comment]
Ok. No problem. Thanks

**Comment by zky001** [comment]
@manetivinay do you find how to solve this problem?

**Comment by manetivinay** [comment]
Hi Jielse,


No I didn't find the solution.

**Comment by jlelse** [comment]
It must be in relation to a wrong JDK version. Make sure you chose jdk 8 everywhere.

**Comment by manetivinay** [comment]
Yes. I try to use jdk 8.  Even I have attached you image in github issue.

**Comment by jlelse** [comment]
@manetivinay I know, but I don't know why this issue appears

**Comment by manetivinay** [comment]
I was try to search in Google, but I have applied what they where saying.
But it didn't resolve my  issue.

**Comment by djKooks** [comment]
@manetivinay What is your version of Android Studio? Would you try on 2.2 stable?

**Comment by manetivinay** [comment]
@djKooks @jlelse Works fine with Android studio 2.2 stable version. Thank you 👍

**Comment by djKooks** [comment]
@manetivinay Good news~I'm not sure, but it looks like something in Android 2.1 is referring old java 7 because as I know version 51.0 means JDK 1.7. Good luck~

**Comment by manetivinay** [comment]
Ahh.. Ok.

**Comment by jlelse** [comment]
Ah ok this was the issue. because I used IDEA and not AS and now AS 2.2.

**Comment by manetivinay** [comment]
@jlelse Ok cool. Now the issue is solved and I can build successfully 👍
